### ISSUE TITLE
proxy problem

### ISSUE THREAD

**Issue by miclar** [Microsoft/vscode-spring-initializr#67]
Extension doesn't seem to work behind a company proxy. Getting: 
[2018-08-14 14:11:24.194] [renderer1] [error] connect ECONNREFUSED 104.17.46.2:80: Error: connect ECONNREFUSED 104.17.46.2:80
	at Object._errnoException (util.js:1024:11)
	at _exceptionWithHostPort (util.js:1046:20)
	at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)

**Comment by miclar** [comment]
Proxy issues, manage to solved them myself.

**Comment by joepace2012** [comment]
> y issues, manage to solved them myself.

miclar, can you tell how you resolved.
